services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: laravel-app
    working_dir: /var/www/html
    # For dev: mount code so you can edit live. In prod, drop this volume.
    volumes:
      - ./:/var/www/html
    env_file:
      - ./backend/.env.docker
    depends_on:
      - mysql

  nginx:
    image: nginx:1.27-alpine
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
